GE.contentType ={
"ext.*":"application/octet-stream","ext.001":"application/x-001","ext.301":"application/x-301" ,
"ext.323":"text/h323" ,"ext.906":"application/x-906" ,"ext.907":"drawing/907" ,"ext.a11":"application/x-a11" ,
"ext.acp":"audio/x-mei-aac" ,"ext.ai":"application/postscript" ,"ext.aif":"audio/aiff" ,"ext.aifc":"audio/aiff" ,
"ext.aiff":"audio/aiff" ,"ext.anv":"application/x-anv" ,"ext.asa":"text/asa" ,"ext.asf":"video/x-ms-asf" ,"ext.asp":"text/asp" ,
"ext.asx":"video/x-ms-asf" ,"ext.au":"audio/basic" ,"ext.avi":"video/avi" ,"ext.awf":"application/vnd.adobe.workflow" ,
"ext.biz":"text/xml" ,"ext.bmp":"application/x-bmp" ,"ext.bot":"application/x-bot" ,"ext.c4t":"application/x-c4t" ,
"ext.c90":"application/x-c90" ,"ext.cal":"application/x-cals" ,"ext.cat":"application/vnd.ms-pki.seccat" ,"ext.cdf":"application/x-netcdf" ,
"ext.cdr":"application/x-cdr" ,"ext.cel":"application/x-cel" ,"ext.cer":"application/x-x509-ca-cert" ,"ext.cg4":"application/x-g4" ,
"ext.cgm":"application/x-cgm" ,"ext.cit":"application/x-cit" ,"ext.class":"java/*" ,"ext.cml":"text/xml" ,
"ext.cmp":"application/x-cmp" ,"ext.cmx":"application/x-cmx" ,"ext.cot":"application/x-cot" ,"ext.crl":"application/pkix-crl" ,
"ext.crt":"application/x-x509-ca-cert" ,"ext.csi":"application/x-csi" ,"ext.css":"text/css" ,"ext.cut":"application/x-cut" ,
"ext.dbf":"application/x-dbf" ,"ext.dbm":"application/x-dbm" ,"ext.dbx":"application/x-dbx" ,"ext.dcd":"text/xml" ,
"ext.dcx":"application/x-dcx" ,"ext.der":"application/x-x509-ca-cert" ,"ext.dgn":"application/x-dgn" ,"ext.dib":"application/x-dib" ,
"ext.dll":"application/x-msdownload" ,"ext.doc":"application/msword" ,"ext.dot":"application/msword" ,
"ext.drw":"application/x-drw" ,"ext.dtd":"text/xml" ,"ext.dwf":"Model/vnd.dwf" ,"ext.dwf":"application/x-dwf" ,
"ext.dwg":"application/x-dwg" ,"ext.dxb":"application/x-dxb" ,"ext.dxf":"application/x-dxf" ,"ext.edn":"application/vnd.adobe.edn" ,
"ext.emf":"application/x-emf" ,"ext.eml":"message/rfc822" ,"ext.ent":"text/xml" ,"ext.epi":"application/x-epi" ,
"ext.eps":"application/x-ps" ,"ext.eps":"application/postscript" ,"ext.etd":"application/x-ebx" ,"ext.exe":"application/x-msdownload" ,
"ext.fax":"image/fax" ,"ext.fdf":"application/vnd.fdf" ,"ext.fif":"application/fractals" ,"ext.fo":"text/xml" ,"ext.frm":"application/x-frm" ,
"ext.g4":"application/x-g4" ,"ext.gbr":"application/x-gbr" ,"ext.gcd":"application/x-gcd" ,"ext.gif":"image/gif" ,
"ext.gl2":"application/x-gl2" ,"ext.gp4":"application/x-gp4" ,"ext.hgl":"application/x-hgl" ,"ext.hmr":"application/x-hmr" ,
"ext.hpg":"application/x-hpgl" ,"ext.hpl":"application/x-hpl" ,"ext.hqx":"application/mac-binhex40" ,"ext.hrf":"application/x-hrf" ,
"ext.hta":"application/hta" ,"ext.htc":"text/x-component" ,"ext.htm":"text/html" ,"ext.html":"text/html" ,
"ext.htt":"text/webviewhtml" ,"ext.htx":"text/html" ,"ext.icb":"application/x-icb" ,"ext.ico":"image/x-icon" ,
"ext.ico":"application/x-ico" ,"ext.iff":"application/x-iff" ,"ext.ig4":"application/x-g4" ,"ext.igs":"application/x-igs" ,
"ext.iii":"application/x-iphone" ,"ext.img":"application/x-img" ,"ext.ins":"application/x-internet-signup" ,"ext.isp":"application/x-internet-signup" ,
"ext.IVF":"video/x-ivf" ,"ext.java":"java/*" ,"ext.jfif":"image/jpeg" ,"ext.jpe":"image/jpeg" ,"ext.jpe":"application/x-jpe" ,
"ext.jpeg":"image/jpeg" ,"ext.jpg":"image/jpeg" ,"ext.jpg":"application/x-jpg" ,"ext.js":"application/x-javascript" ,
"ext.jsp":"text/html" ,"ext.la1":"audio/x-liquid-file" ,"ext.lar":"application/x-laplayer-reg" ,"ext.latex":"application/x-latex" ,
"ext.lavs":"audio/x-liquid-secure" ,"ext.lbm":"application/x-lbm" ,"ext.lmsff":"audio/x-la-lms" ,"ext.ls":"application/x-javascript" ,
"ext.ltr":"application/x-ltr" ,"ext.m1v":"video/x-mpeg" ,"ext.m2v":"video/x-mpeg" ,"ext.m3u":"audio/mpegurl" ,
"ext.m4e":"video/mpeg4" ,"ext.mac":"application/x-mac" ,"ext.man":"application/x-troff-man" ,"ext.math":"text/xml" ,
"ext.mdb":"application/msaccess" ,"ext.mdb":"application/x-mdb" ,"ext.mfp":"application/x-shockwave-flash" ,"ext.mht":"message/rfc822" ,
"ext.mhtml":"message/rfc822" ,"ext.mi":"application/x-mi" ,"ext.mid":"audio/mid" ,"ext.midi":"audio/mid" ,
"ext.mil":"application/x-mil" ,"ext.mml":"text/xml" ,"ext.mnd":"audio/x-musicnet-download" ,"ext.mns":"audio/x-musicnet-stream" ,
"ext.mocha":"application/x-javascript" ,"ext.movie":"video/x-sgi-movie" ,"ext.mp1":"audio/mp1" ,"ext.mp2":"audio/mp2" ,
"ext.mp2v":"video/mpeg" ,"ext.mp3":"audio/mp3" ,"ext.mp4":"video/mpeg4" ,"ext.mpa":"video/x-mpg" ,"ext.mpd":"application/vnd.ms-project" ,
"ext.mpe":"video/x-mpeg" ,"ext.mpeg":"video/mpg" ,"ext.mpg":"video/mpg" ,"ext.mpga":"audio/rn-mpeg" ,
"ext.mpp":"application/vnd.ms-project" ,"ext.mps":"video/x-mpeg" ,"ext.mpt":"application/vnd.ms-project" ,"ext.mpv":"video/mpg" ,
"ext.mpv2":"video/mpeg" ,"ext.mpw":"application/vnd.ms-project" ,"ext.mpx":"application/vnd.ms-project" ,"ext.mtx":"text/xml" ,
"ext.mxp":"application/x-mmxp" ,"ext.net":"image/pnetvue" ,"ext.nrf":"application/x-nrf" ,"ext.nws":"message/rfc822" ,
"ext.odc":"text/x-ms-odc" ,"ext.out":"application/x-out" ,"ext.p10":"application/pkcs10" ,"ext.p12":"application/x-pkcs12" ,
"ext.p7b":"application/x-pkcs7-certificates" ,"ext.p7c":"application/pkcs7-mime" ,"ext.p7m":"application/pkcs7-mime" ,
"ext.p7r":"application/x-pkcs7-certreqresp" ,"ext.p7s":"application/pkcs7-signature" ,"ext.pc5":"application/x-pc5" ,
"ext.pci":"application/x-pci" ,"ext.pcl":"application/x-pcl" ,"ext.pcx":"application/x-pcx" ,"ext.pdf":"application/pdf" ,
"ext.pdf":"application/pdf" ,"ext.pdx":"application/vnd.adobe.pdx" ,"ext.pfx":"application/x-pkcs12" ,"ext.pgl":"application/x-pgl" ,
"ext.pic":"application/x-pic" ,"ext.pko":"application/vnd.ms-pki.pko" ,"ext.pl":"application/x-perl" ,"ext.plg":"text/html" ,
"ext.pls":"audio/scpls" ,"ext.plt":"application/x-plt" ,"ext.png":"image/png" ,"ext.png":"application/x-png" ,
"ext.pot":"application/vnd.ms-powerpoint" ,"ext.ppa":"application/vnd.ms-powerpoint" ,"ext.ppm":"application/x-ppm" ,"ext.pps":"application/vnd.ms-powerpoint" ,
"ext.ppt":"application/vnd.ms-powerpoint" ,"ext.ppt":"application/x-ppt" ,"ext.pr":"application/x-pr" ,"ext.prf":"application/pics-rules" ,
"ext.prn":"application/x-prn" ,"ext.prt":"application/x-prt" ,"ext.ps":"application/x-ps" ,"ext.ps":"application/postscript" ,
"ext.ptn":"application/x-ptn" ,"ext.pwz":"application/vnd.ms-powerpoint" ,"ext.r3t":"text/vnd.rn-realtext3d" ,"ext.ra":"audio/vnd.rn-realaudio" ,
"ext.ram":"audio/x-pn-realaudio" ,"ext.ras":"application/x-ras" ,"ext.rat":"application/rat-file" ,"ext.rdf":"text/xml" ,
"ext.rec":"application/vnd.rn-recording" ,"ext.red":"application/x-red" ,"ext.rgb":"application/x-rgb" ,"ext.rjs":"application/vnd.rn-realsystem-rjs" ,
"ext.rjt":"application/vnd.rn-realsystem-rjt" ,"ext.rlc":"application/x-rlc" ,"ext.rle":"application/x-rle" ,
"ext.rm":"application/vnd.rn-realmedia" ,"ext.rmf":"application/vnd.adobe.rmf" ,"ext.rmi":"audio/mid" ,"ext.rmj":"application/vnd.rn-realsystem-rmj" ,
"ext.rmm":"audio/x-pn-realaudio" ,"ext.rmp":"application/vnd.rn-rn_music_package" ,"ext.rms":"application/vnd.rn-realmedia-secure" ,"ext.rmvb":"application/vnd.rn-realmedia-vbr" ,
"ext.rmx":"application/vnd.rn-realsystem-rmx" ,"ext.rnx":"application/vnd.rn-realplayer" ,"ext.rp":"image/vnd.rn-realpix" ,
"ext.rpm":"audio/x-pn-realaudio-plugin" ,"ext.rsml":"application/vnd.rn-rsml" ,"ext.rt":"text/vnd.rn-realtext" ,
"ext.rtf":"application/msword" ,"ext.rtf":"application/x-rtf" ,"ext.rv":"video/vnd.rn-realvideo" ,
"ext.sam":"application/x-sam" ,".sat":"application/x-sat" ,"ext.sdp":"application/sdp" ,"ext.sdw":"application/x-sdw" ,
"ext.sit":"application/x-stuffit" ,"ext.slb":"application/x-slb" ,"ext.sld":"application/x-sld" ,"ext.slk":"drawing/x-slk" ,
"ext.smi":"application/smil" ,"ext.smil":"application/smil" ,"ext.smk":"application/x-smk" ,"ext.snd":"audio/basic" ,
"ext.sol":"text/plain" ,"ext.sor":"text/plain" ,"ext.spc":"application/x-pkcs7-certificates" ,"ext.spl":"application/futuresplash" ,
"ext.spp":"text/xml" ,"ext.ssm":"application/streamingmedia" ,"ext.sst":"application/vnd.ms-pki.certstore" ,"ext.stl":"application/vnd.ms-pki.stl" ,
"ext.stm":"text/html" ,"ext.sty":"application/x-sty" ,"ext.svg":"text/xml" ,"ext.swf":"application/x-shockwave-flash" ,
"ext.tdf":"application/x-tdf" ,"ext.tg4":"application/x-tg4" ,"ext.tga":"application/x-tga" ,"ext.tif":"image/tiff" ,
"ext.tif":"application/x-tif" ,"ext.tiff":"image/tiff" ,"ext.tld":"text/xml" ,"ext.top":"drawing/x-top" ,"ext.torrent":"application/x-bittorrent" ,
"ext.tsd":"text/xml" ,"ext.txt":"text/plain" ,"ext.uin":"application/x-icq" ,"ext.uls":"text/iuls" ,"ext.vcf":"text/x-vcard" ,
"ext.vda":"application/x-vda" ,"ext.vdx":"application/vnd.visio" ,"ext.vml":"text/xml" ,"ext.vpg":"application/x-vpeg005" ,
"ext.vsd":"application/vnd.visio" ,"ext.vsd":"application/x-vsd" ,"ext.vss":"application/vnd.visio" ,"ext.vst":"application/vnd.visio" ,
"ext.vst":"application/x-vst" ,"ext.vsw":"application/vnd.visio" ,"ext.vsx":"application/vnd.visio" ,"ext.vtx":"application/vnd.visio" ,
"ext.vxml":"text/xml" ,"ext.wav":"audio/wav" ,"ext.wax":"audio/x-ms-wax" ,"ext.wb1":"application/x-wb1" ,
"ext.wb2":"application/x-wb2" ,"ext.wb3":"application/x-wb3" ,"ext.wbmp":"image/vnd.wap.wbmp" ,"ext.wiz":"application/msword" ,
"ext.wk3":"application/x-wk3" ,"ext.wk4":"application/x-wk4" ,"ext.wkq":"application/x-wkq" ,"ext.wks":"application/x-wks" ,
"ext.wm":"video/x-ms-wm" ,"ext.wma":"audio/x-ms-wma" ,"ext.wmd":"application/x-ms-wmd" ,"ext.wmf":"application/x-wmf" ,
"ext.wml":"text/vnd.wap.wml" ,"ext.wmv":"video/x-ms-wmv" ,"ext.wmx":"video/x-ms-wmx" ,"ext.wmz":"application/x-ms-wmz" ,
"ext.wp6":"application/x-wp6" ,"ext.wpd":"application/x-wpd" ,"ext.wpg":"application/x-wpg" ,"ext.wpl":"application/vnd.ms-wpl" ,
"ext.wq1":"application/x-wq1" ,"ext.wr1":"application/x-wr1" ,"ext.wri":"application/x-wri" ,"ext.wrk":"application/x-wrk" ,
"ext.ws":"application/x-ws" ,"ext.ws2":"application/x-ws" ,"ext.wsc":"text/scriptlet" ,"ext.wsdl":"text/xml" ,"ext.wvx":"video/x-ms-wvx" ,
"ext.xdp":"application/vnd.adobe.xdp" ,"ext.xdr":"text/xml" ,"ext.xfd":"application/vnd.adobe.xfd" ,"ext.xfdf":"application/vnd.adobe.xfdf" ,
"ext.xhtml":"text/html" ,"ext.xls":"application/vnd.ms-excel" ,"ext.xls":"application/x-xls" ,"ext.xlw":"application/x-xlw" ,
"ext.xml":"text/xml" ,"ext.xpl":"audio/scpls" ,"ext.xq":"text/xml" ,"ext.xql":"text/xml" ,"ext.xquery":"text/xml" ,
"ext.xsd":"text/xml" ,"ext.xsl":"text/xml" ,"ext.xslt":"text/xml" ,"ext.xwd":"application/x-xwd" ,"ext.x_b":"application/x-x_b" ,
"ext.x_t":"application/x-x_t"
};

GE.commonErrorCode ={
	"200" :{name : "OK",description: "请求执行成功"},
	"201" :{name : "PARTIAL_ERROR", description: "批量请求部分执行成功"},
	"400" :{name : "BAD_REQUEST", description: "请求错误(参数缺失、格式错误、值非法等)"},
	"403" :{name : "OPERATION_FORBIDDEN", description: "非法操作（缺少权限等）"}, 
  "401" :{name : "CERT_ERROR",description: "用户凭证非法（验证失败)"},
  "408" :{name : "REQUEST_TIMEOUT",description:"请求超时（未能在指定时间内执行请求完成)"},
  "500" :{name : "INTERNAL_SERVER_ERROR",description:"服务器内部错误。"},
  "501" :{name : "NOT_IMPLEMENTED",description: "服务未实现。"},
	"503" :{name : "SERVICE_UNAVAILABLE",description: "服务不可用"},
  "550" :{name : "PRODUCT_NOT_FOUND",description: "产品不存在"},
  "551" :{name : "USER_ORG_NOT_FOUND",description: "企业（或组织）不存在"}, 
  "552" :{name : "USER_TYPE_NOT_FOUND",description: "用户类型不存在"},
  "553" :{name : "USER_NOT_FOUND",description: "用户不存在"},
  "554" :{name : "DOMAIN_NOT_FOUND",description: " 用户文件域不存在。"},
  "555" :{name : "FILE_NOT_FOUND",description: "  文件不存在。"},
  "556" :{name : "FILE_VER_NOT_FOUND",description: " 文件版本不存在。"},
  "557" :{name : "DOC_NOT_FOUND",description: " 存储文件不存在。"},
  "600" :{name :  "FILE_SIZE_LIMIT_EXCEED",description: " 文件大小超限。"},
  "601" :{name :  "FILE_NOT_COMPLETE",description: " 文件未上传完成（未完整）。"},
  "602" :{name :  "FILE_NOT_SHARED",description: " 文件未共享或下载码不正确。"},
  "603" :{name :  "FILE_EXPIRED",description: " 文件已过期。"},
  "604" :{name :  "FILE_URL_ILLEGAL",description: " 文件共享URL非法。"},
  "605" :{name :   "FILE_UD_CONTEXT_ILLEGAL",description: " 文件上传控制上下文（产品）非法。"},
  "606" :{name :  "FILE_DD_CONTEXT_ILLEGAL",description: " 文件下载控制上下文（产品）非法。"},
  "607" :{name :  "FILE_SHARE_KEY_INVALID",description: " 文件下载码非法。"},
  "608" :{name :  "FILE_RENEW_USEDUP",description: " 文件无剩余可续期次数。"},
  "609" :{name :  "FILE_DD_COUNT_USEDUP",description: " 文件无剩余下载次数。"},
  "610" :{name :  "FILE_VER_CONFLICT",description: " 文件版本冲突。"},
  "611" :{name :  "FILE_NAME_CONFLICT",description: " 文件名冲突。"},
  "650" :{name :  "FILE_SHARE_NOT_FOUND",description: " 文件共享信息不存在。"},
  "651" :{name :  "FILE_SHARE_KEY_ILLEGAL",description: " 文件共享下载码非法。"},
  "700" :{name :  "DIR_PATH_ILLEGAL",description: " 目录路径非法。"},
  "701" :{name :  "DIR_RECURSIVE_ACT_DENIED",description: " 目录层级操作被拒绝。"},
  "702" :{name :  "DIR_NOT_EMPTY",description: " 对非空目录执行操作失败（如删除）。"},
  "703" :{name :  "DIR_NAME_CONFLICT",description: " 目录名冲突。"},
  "704" :{name :  "DIR_NOT_EXIST",description: " 目录不存在。"},
  "800" :{name :  "USER_CAPACITY_EXCEED" ,description: "用户容量超限。"},
	"1000":{name :  "DOC_NOT_FOUND",description: " 存储文件不存在。"},
  "1001":{name :  "DOC_CHECKSUM_ERROR",description: " 存储文件校验值错误。"},
  "1002":{name :  "DATA_DESCRIPTOR_INVALID",description: " 数据块元数据错误。"},
  "1003":{name :  "DATA_DESCRIPTOR_CHECKSUM_FAILED",description: " 数据块元数据校验失败。"},
  "1004":{name :  "DATA_INVALID",description: " 数据块错误（与元数据描述不匹配）。"},
  "1005":{name :  "DATA_CHECKSUM_FAILED",description: " 数据块校验失败。"}
};





